name: my-whisper
services:
  train:
    build:
      context: "."
      platforms: ["linux/amd64"]
      tags: ["tesstt"]
    container_name: my-container
    command: ["train.py"]
    volumes:
    - ~/.cache:/workspace/cache
    - ~/coder/whisper:/workspace/my-whisper-lora
    environment:
    - HF_TOKEN=███
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            capabilities: [gpu]
            count: all
