name: my-whisper
services:
  train:
    build:
      context: "."
      platforms: ["linux/amd64"]
      tags: ["tesstt"]
    # image: "<username>/<my-repo>:<tag>"
    container_name: my-container
    command: ["python", "train.py", "-total-steps", "30", "-batch-size", "4"]
    volumes:
    - ~/whisper:/workspace
    environment:
    - OMP_NUM_THREADS=1
    - HF_TOKEN=███
    # ipc: host
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            capabilities: [gpu]
            count: all
